version: '3.8'

services:
  buildhive-api:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: buildhive-api
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://${DB_USER:-buildhive}:${DB_PASSWORD:-buildhive123}@postgres:5432/${DB_NAME:-buildhive_db}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3001}
      - API_BASE_URL=${API_BASE_URL:-http://localhost:3000}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - buildhive-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: buildhive-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-buildhive_db}
      POSTGRES_USER: ${DB_USER:-buildhive}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-buildhive123}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped
    networks:
      - buildhive-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-buildhive} -d ${DB_NAME:-buildhive_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: buildhive-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-buildhive_redis}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - buildhive-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: buildhive-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - buildhive-api
    restart: unless-stopped
    networks:
      - buildhive-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  buildhive-network:
    driver: bridge
