services:
  - type: web
    name: buildhive-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: API_VERSION
        value: v1
      - key: APP_NAME
        value: BuildHive
      - key: DATABASE_URL
        fromDatabase:
          name: BuildHive-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: BuildHive-Redis
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: COOKIE_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://buildhive.com,https://www.buildhive.com
      - key: API_BASE_URL
        value: https://buildhive-api.onrender.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: ALLOWED_FILE_TYPES
        value: image/jpeg,image/png,image/gif,application/pdf
      - key: LOG_LEVEL
        value: info
      - key: LOG_FORMAT
        value: json
      - key: ENABLE_REQUEST_LOGGING
        value: true
      - key: ENABLE_REGISTRATION
        value: true
      - key: ENABLE_EMAIL_VERIFICATION
        value: true
      - key: ENABLE_PHONE_VERIFICATION
        value: true
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_FROM
        value: noreply@buildhive.com
      - key: EMAIL_FROM_NAME
        value: BuildHive
      - key: AWS_S3_BUCKET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: ap-southeast-2
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: ABN_LOOKUP_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://buildhive-api.onrender.com/api/v1/auth/google/callback

    disk:
      name: buildhive-storage
      mountPath: /app/storage
      sizeGB: 1

databases:
  - name: BuildHive-db

services:
  - type: redis
    name: BuildHive-Redis

previewsEnabled: true
previewsExpireAfterDays: 7
