import { UserRole, UserStatus, AuthProvider } from '../../shared/types';

export const AUTH_CONSTANTS = {
  USER_ROLES: {
    CLIENT: UserRole.CLIENT,
    TRADIE: UserRole.TRADIE,
    ENTERPRISE: UserRole.ENTERPRISE
  },
  
  USER_STATUS: {
    PENDING: UserStatus.PENDING,
    ACTIVE: UserStatus.ACTIVE,
    SUSPENDED: UserStatus.SUSPENDED
  },
  
  AUTH_PROVIDERS: {
    LOCAL: AuthProvider.LOCAL,
    GOOGLE: AuthProvider.GOOGLE,
    LINKEDIN: AuthProvider.LINKEDIN,
    FACEBOOK: AuthProvider.FACEBOOK
  },
  
  PASSWORD_REQUIREMENTS: {
    MIN_LENGTH: 8,
    MAX_LENGTH: 128,
    REQUIRE_UPPERCASE: true,
    REQUIRE_LOWERCASE: true,
    REQUIRE_NUMBERS: true,
    REQUIRE_SPECIAL_CHARS: true
  },
  
  USERNAME_REQUIREMENTS: {
    MIN_LENGTH: 3,
    MAX_LENGTH: 30,
    ALLOWED_PATTERN: /^[a-zA-Z0-9_-]+$/
  },
  
  EMAIL_REQUIREMENTS: {
    MAX_LENGTH: 254,
    PATTERN: /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  },
  
  RATE_LIMITS: {
    REGISTRATION: {
      WINDOW_MS: 15 * 60 * 1000,
      MAX_ATTEMPTS: 5
    },
    EMAIL_VERIFICATION: {
      WINDOW_MS: 60 * 60 * 1000,
      MAX_ATTEMPTS: 3
    },
    LOGIN: {
      WINDOW_MS: 15 * 60 * 1000,
      MAX_ATTEMPTS: 5
    },
    PASSWORD_RESET: {
      WINDOW_MS: 60 * 60 * 1000,
      MAX_ATTEMPTS: 3
    },
    CHANGE_PASSWORD: {
      WINDOW_MS: 60 * 60 * 1000,
      MAX_ATTEMPTS: 3
    }
  },
  
  TOKEN_TYPES: {
    ACCESS: 'access',
    REFRESH: 'refresh',
    EMAIL_VERIFICATION: 'email_verification',
    PASSWORD_RESET: 'password_reset'
  },
  
  SESSION_TYPES: {
    ACCESS: 'access',
    REFRESH: 'refresh',
    PASSWORD_RESET: 'password_reset'
  },
  
  VERIFICATION_CODE: {
    LENGTH: 6,
    EXPIRES_IN_MINUTES: 15,
    MAX_ATTEMPTS: 3
  },
  
  PASSWORD_RESET: {
    TOKEN_EXPIRES_MINUTES: 30,
    MAX_ATTEMPTS: 3,
    COOLDOWN_MINUTES: 5
  },
  
  REFRESH_TOKEN: {
    EXPIRES_IN: '7d',
    ROTATION_ENABLED: true
  },
  
  LOGIN_ATTEMPTS: {
    MAX_ATTEMPTS: 5,
    LOCKOUT_DURATION_MINUTES: 15,
    RESET_TIME_MINUTES: 60
  }
} as const;

export const HTTP_STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500
} as const;

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  USER_EXISTS: 'USER_EXISTS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  USERNAME_EXISTS: 'USERNAME_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  PASSWORD_RESET_REQUIRED: 'PASSWORD_RESET_REQUIRED',
  INVALID_PASSWORD_RESET_TOKEN: 'INVALID_PASSWORD_RESET_TOKEN',
  PASSWORD_RESET_EXPIRED: 'PASSWORD_RESET_EXPIRED',
  SAME_PASSWORD: 'SAME_PASSWORD',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

