import { MARKETPLACE_JOB_TYPES, URGENCY_LEVEL, MARKETPLACE_CREDIT_COSTS, MARKETPLACE_LIMITS } from './constants';

export const MARKETPLACE_CONFIG = {
  APPLICATION_SETTINGS: {
    MAX_APPLICATIONS_PER_TRADIE_PER_DAY: 20,
    MAX_APPLICATIONS_PER_JOB: 50,
    APPLICATION_EXPIRY_HOURS: 72,
    AUTO_REJECT_AFTER_DAYS: 7,
    ALLOW_APPLICATION_WITHDRAWAL: true,
    WITHDRAWAL_DEADLINE_HOURS: 24
  },
  
  JOB_POSTING_SETTINGS: {
    DEFAULT_EXPIRY_DAYS: 30,
    MAX_EXPIRY_DAYS: 60,
    MIN_EXPIRY_DAYS: 1,
    AUTO_PUBLISH: true,
    REQUIRE_CLIENT_VERIFICATION: false,
    ALLOW_BUDGET_RANGE: true,
    REQUIRE_PHOTOS: false,
    MAX_PHOTOS_PER_JOB: 10
  },

  CREDIT_SYSTEM: {
    BASE_COST: MARKETPLACE_CREDIT_COSTS.BASE_APPLICATION_COST,
    URGENCY_MULTIPLIERS: MARKETPLACE_CREDIT_COSTS.URGENCY_MULTIPLIERS,
    JOB_TYPE_MULTIPLIERS: MARKETPLACE_CREDIT_COSTS.JOB_TYPE_MULTIPLIERS,
    REFUND_POLICY: {
      ALLOW_REFUNDS: true,
      REFUND_WINDOW_HOURS: 24,
      REFUND_CONDITIONS: ['job_cancelled', 'duplicate_application', 'system_error'],
      PARTIAL_REFUND_PERCENTAGE: 50
    },
    BULK_APPLICATION_DISCOUNTS: {
      TIER_1: { min_applications: 5, discount_percentage: 5 },
      TIER_2: { min_applications: 10, discount_percentage: 10 },
      TIER_3: { min_applications: 20, discount_percentage: 15 }
    }
  },

  SELECTION_PROCESS: {
    AUTO_SELECTION_ENABLED: false,
    SELECTION_DEADLINE_DAYS: 14,
    NOTIFY_UNSELECTED_AFTER_HOURS: 48,
    ALLOW_NEGOTIATION: true,
    MAX_NEGOTIATION_ROUNDS: 3,
    REQUIRE_SELECTION_REASON: false
  },

  SEARCH_AND_FILTERING: {
    DEFAULT_RADIUS_KM: 25,
    MAX_RADIUS_KM: 100,
    ENABLE_LOCATION_BASED_SEARCH: true,
    ENABLE_BUDGET_FILTERING: true,
    ENABLE_DATE_FILTERING: true,
    CACHE_SEARCH_RESULTS: true,
    SEARCH_CACHE_TTL_MINUTES: 5
  },

  NOTIFICATION_SETTINGS: {
    NOTIFY_NEW_JOBS: true,
    NOTIFY_APPLICATION_STATUS: true,
    NOTIFY_SELECTION_RESULTS: true,
    NOTIFY_JOB_EXPIRY: true,
    EMAIL_NOTIFICATIONS: true,
    SMS_NOTIFICATIONS: false,
    PUSH_NOTIFICATIONS: true,
    NOTIFICATION_BATCH_SIZE: 100
  },

  ANALYTICS_CONFIG: {
    TRACK_APPLICATION_METRICS: true,
    TRACK_CONVERSION_RATES: true,
    TRACK_CREDIT_USAGE: true,
    TRACK_GEOGRAPHIC_DATA: true,
    RETENTION_PERIOD_DAYS: 365,
    AGGREGATE_DAILY_STATS: true,
    REAL_TIME_DASHBOARD: true
  },

  QUALITY_CONTROL: {
    ENABLE_JOB_MODERATION: false,
    AUTO_APPROVE_VERIFIED_CLIENTS: true,
    FLAG_SUSPICIOUS_JOBS: true,
    MIN_JOB_DESCRIPTION_LENGTH: MARKETPLACE_LIMITS.JOB_DESCRIPTION_MIN_LENGTH,
    MAX_BUDGET_VARIANCE_PERCENTAGE: 200,
    REQUIRE_REALISTIC_TIMELINES: true
  },

  PERFORMANCE_SETTINGS: {
    ENABLE_CACHING: true,
    CACHE_TTL_SECONDS: 300,
    ENABLE_PAGINATION: true,
    DEFAULT_PAGE_SIZE: 20,
    MAX_PAGE_SIZE: 100,
    ENABLE_LAZY_LOADING: true,
    DATABASE_CONNECTION_POOL_SIZE: 20
  },

  SECURITY_SETTINGS: {
    RATE_LIMIT_APPLICATIONS: true,
    PREVENT_SPAM_APPLICATIONS: true,
    VALIDATE_CLIENT_CONTACT_INFO: true,
    SANITIZE_JOB_DESCRIPTIONS: true,
    ENABLE_FRAUD_DETECTION: true,
    LOG_ALL_TRANSACTIONS: true,
    ENCRYPT_SENSITIVE_DATA: true
  },

  INTEGRATION_SETTINGS: {
    SYNC_WITH_JOB_MANAGEMENT: true,
    SYNC_WITH_CRM: true,
    SYNC_WITH_CREDIT_SYSTEM: true,
    ENABLE_WEBHOOK_NOTIFICATIONS: true,
    EXTERNAL_API_TIMEOUT_MS: 30000,
    RETRY_FAILED_INTEGRATIONS: true,
    MAX_RETRY_ATTEMPTS: 3
  },

  BUSINESS_RULES: {
    ALLOW_MULTIPLE_APPLICATIONS: true,
    REQUIRE_COMPLETE_PROFILE: true,
    MIN_CREDIT_BALANCE_FOR_APPLICATION: 1,
    ALLOW_QUOTE_MODIFICATIONS: true,
    ENABLE_AUTOMATIC_MATCHING: false,
    PRIORITY_BOOST_FOR_PREMIUM_USERS: false
  },

  GEOGRAPHIC_SETTINGS: {
    DEFAULT_COUNTRY: 'AU',
    DEFAULT_CURRENCY: 'AUD',
    ENABLE_MULTI_LOCATION_JOBS: false,
    LOCATION_PRECISION_LEVEL: 'suburb',
    AUTO_DETECT_LOCATION: true,
    VALIDATE_POSTCODES: true
  },

  COMMUNICATION_SETTINGS: {
    ENABLE_IN_APP_MESSAGING: false,
    ALLOW_DIRECT_CONTACT_AFTER_SELECTION: true,
    MASK_CONTACT_INFO_BEFORE_SELECTION: true,
    ENABLE_VIDEO_CONSULTATIONS: false,
    MESSAGE_RETENTION_DAYS: 90
  },

  MARKETPLACE_FEATURES: {
    ENABLE_JOB_TEMPLATES: false,
    ENABLE_SAVED_SEARCHES: true,
    ENABLE_JOB_ALERTS: true,
    ENABLE_TRADIE_FAVORITES: false,
    ENABLE_JOB_SHARING: true,
    ENABLE_BULK_OPERATIONS: false
  },

  REPORTING_CONFIG: {
    GENERATE_DAILY_REPORTS: true,
    GENERATE_WEEKLY_SUMMARIES: true,
    GENERATE_MONTHLY_ANALYTICS: true,
    EMAIL_REPORTS_TO_ADMINS: true,
    INCLUDE_FINANCIAL_METRICS: true,
    INCLUDE_PERFORMANCE_METRICS: true,
    REPORT_RETENTION_MONTHS: 12
  },

  MAINTENANCE_SETTINGS: {
    AUTO_CLEANUP_EXPIRED_JOBS: true,
    CLEANUP_FREQUENCY_HOURS: 24,
    ARCHIVE_OLD_APPLICATIONS: true,
    ARCHIVE_AFTER_DAYS: 90,
    OPTIMIZE_DATABASE_WEEKLY: true,
    BACKUP_FREQUENCY_HOURS: 6
  }
} as const;

export const MARKETPLACE_FEATURE_FLAGS = {
  ENABLE_ADVANCED_SEARCH: true,
  ENABLE_REAL_TIME_UPDATES: true,
  ENABLE_MOBILE_OPTIMIZATIONS: true,
  ENABLE_OFFLINE_SUPPORT: false,
  ENABLE_DARK_MODE: true,
  ENABLE_ACCESSIBILITY_FEATURES: true,
  ENABLE_MULTI_LANGUAGE: false,
  ENABLE_BETA_FEATURES: false
} as const;

export const MARKETPLACE_ENVIRONMENT_CONFIG = {
  DEVELOPMENT: {
    DEBUG_MODE: true,
    MOCK_EXTERNAL_APIS: true,
    DISABLE_RATE_LIMITING: true,
    ENABLE_TEST_DATA: true,
    LOG_LEVEL: 'debug'
  },
  STAGING: {
    DEBUG_MODE: false,
    MOCK_EXTERNAL_APIS: false,
    DISABLE_RATE_LIMITING: false,
    ENABLE_TEST_DATA: false,
    LOG_LEVEL: 'info'
  },
  PRODUCTION: {
    DEBUG_MODE: false,
    MOCK_EXTERNAL_APIS: false,
    DISABLE_RATE_LIMITING: false,
    ENABLE_TEST_DATA: false,
    LOG_LEVEL: 'error'
  }
} as const;

export const getMarketplaceConfig = (environment: string = 'production') => {
  const baseConfig = MARKETPLACE_CONFIG;
  const envConfig = MARKETPLACE_ENVIRONMENT_CONFIG[environment as keyof typeof MARKETPLACE_ENVIRONMENT_CONFIG] || MARKETPLACE_ENVIRONMENT_CONFIG.PRODUCTION;
  
  return {
    ...baseConfig,
    environment: envConfig,
    features: MARKETPLACE_FEATURE_FLAGS
  };
};
